#!/bin/bash

# Scenario 6: CI/CD Gate in Action
# Demonstrate GitHub Actions blocking deployment

set -e

echo "════════════════════════════════════════════════════════════"
echo "  SCENARIO 6: CI/CD Gate in Action ⛔"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "This scenario demonstrates how the GitHub Actions pipeline"
echo "blocks deployment when contracts are incompatible."
echo ""

echo "📋 Setup:"
echo "   1. Local Pact Broker running"
echo "   2. GitHub Actions workflows configured"
echo "   3. Repository with breaking change"
echo ""

echo "🔄 Simulated Pipeline Steps:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  CONSUMER PIPELINE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Step 1: Test"
echo "  $ npm test"
echo "  ✅ All tests pass (using mock server)"
echo ""

echo "Step 2: Publish Contract"
echo "  $ node scripts/publish-consumer-contract.js"
echo "  ✅ Contract published to broker"
echo "  📊 Version: $GITHUB_SHA"
echo "  🏷️  Tags: main, latest"
echo ""

echo "Step 3: Can-I-Deploy"
echo "  $ node scripts/can-i-deploy-consumer.js"
echo "  🔍 Checking with Pact Broker..."
echo ""
echo "  Computer says no ¯\\_(ツ)_/¯"
echo ""
echo "  CONSUMER       | C.VERSION | PROVIDER            | P.VERSION | SUCCESS?"
echo "  ---------------|-----------|---------------------|-----------|----------"
echo "  payment-client | abc123    | payment-gateway-api | def456    | false ❌"
echo ""
echo "  ❌ Provider has not verified this contract"
echo "  ⛔ DEPLOYMENT BLOCKED"
echo ""

echo "Step 4: Notify"
echo "  💬 PR Comment:"
echo "  ┌─────────────────────────────────────────────────┐"
echo "  │ ⚠️  Consumer Can-I-Deploy Check Failed          │"
echo "  │                                                 │"
echo "  │ The consumer cannot be safely deployed as the   │"
echo "  │ provider has not verified compatibility.        │"
echo "  │                                                 │"
echo "  │ 📊 View results in Pact Broker                  │"
echo "  └─────────────────────────────────────────────────┘"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  PROVIDER PIPELINE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Step 1: Test & Verify"
echo "  $ npm run test:api"
echo "  ✅ API tests pass"
echo ""
echo "  $ npm run test:pact:publish"
echo "  🔄 Verifying consumer contracts..."
echo "  ❌ 3 interactions failed"
echo "  ✅ Verification results published"
echo ""

echo "Step 2: Can-I-Deploy"
echo "  $ node scripts/can-i-deploy-provider.js"
echo "  🔍 Checking with Pact Broker..."
echo ""
echo "  Computer says no ¯\\_(ツ)_/¯"
echo ""
echo "  VERIFICATION RESULTS"
echo "  --------------------"
echo "  ❌ Verification failed for consumer contracts"
echo "  ⛔ DEPLOYMENT BLOCKED"
echo ""

echo "Step 3: Notify"
echo "  💬 PR Comment:"
echo "  ┌─────────────────────────────────────────────────┐"
echo "  │ ⚠️  Provider Can-I-Deploy Check Failed          │"
echo "  │                                                 │"
echo "  │ The provider cannot be safely deployed as       │"
echo "  │ consumer contracts are not compatible.          │"
echo "  │                                                 │"
echo "  │ Failed interactions:                            │"
echo "  │ • GET /api/payments/:id                         │"
echo "  │ • POST /api/payments/settle                     │"
echo "  │ • POST /api/payments/refund                     │"
echo "  │                                                 │"
echo "  │ 📊 View details in Pact Broker                  │"
echo "  └─────────────────────────────────────────────────┘"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "  RESULT: Deployment Gate Activated ⛔"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🚫 What the Gate Prevented:"
echo "   ❌ Deploying incompatible consumer to production"
echo "   ❌ Breaking existing provider functionality"
echo "   ❌ Runtime errors in production"
echo "   ❌ Customer-facing failures"
echo ""
echo "✅ What the Gate Provided:"
echo "   ✅ Early detection of incompatibility"
echo "   ✅ Clear failure reasons in PR"
echo "   ✅ Prevented production incident"
echo "   ✅ Guided developers to fix issues"
echo ""
echo "📊 Gate Workflow:"
echo "   Developer → Push Code → Tests Pass → Publish Contract"
echo "                                              ↓"
echo "                                       Can-I-Deploy?"
echo "                                              ↓"
echo "                              ┌───────────────┴────────────────┐"
echo "                             YES                               NO"
echo "                              ↓                                 ↓"
echo "                        Deploy ✅                          Block ⛔"
echo "                              ↓                                 ↓"
echo "                    Record Deployment                   Notify Developer"
echo ""
echo "💡 Real-World Impact:"
echo "   • Prevented 3 breaking changes this sprint"
echo "   • Saved 8 hours of debugging time"
echo "   • Zero production incidents"
echo "   • Increased deployment confidence"
echo ""
echo "🎯 To test this in GitHub Actions:"
echo "   1. Make a breaking change"
echo "   2. Commit and push"
echo "   3. Watch Actions tab"
echo "   4. See gate in action!"
echo ""
